apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-app
  template:
    metadata:
      name: emp-app
      labels:
        app: emp-app
    spec:
      containers:
        - name: emp-app
          image: a30sham/employeeapp
          ports:
           - containerPort: 8080         
---
apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:                     
  name: emp-app           # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: emp-app
spec:                         
  type: LoadBalancer              # The service will be exposed by opening a Port on each node and proxying it. 
  selector:
    app: emp-app          # The service exposes Pods with label `app=polling-app-server`
  ports:                      # Forward incoming connections on port 8080 to the target port 8081
  - name: http
    port: 8080
    targetPort: 8080
